drivers: fix merge conflict
../drivers/net/usb/usbnet.c:2306:18: error: use of undeclared identifier 'node_id'; did you mean 'zone_id'?
        eth_random_addr(node_id);