script: Fix missing terminating character in compile.h
Refer to: https://github.com/LineageOS/android_kernel_sony_sm8250/blob/lineage-21/scripts/mkcompile_h#L76
Add "-m1" for grep to fix the following issues without hardcode compiler name (https://github.com/crdroidandroid/android_kernel_xiaomi_thyme/commit/24b147d266122e5464a358725a23dc9c23cb1a1c):
- Warnings and errors about missing terminating '"' character and unknown type name '__s8'
  while compiling include/generated/compile.h

Before the fix, the error messages were as follows:
In file included from ../../../../../../kernel/sony/sm8150/init/version.c:9:
./include/generated/compile.h:7:24: warning: missing terminating '"' character [-Winvalid-pp-token]
    7 | #define LINUX_COMPILER "Android (11368308, +pgo, +bolt, +lto, +mlgo, based on r510928) clang version 18.0.0 (https://android.googlesource.com/toolchain/llvm-project 477610d4d0d988e69dbc3fae4fe86bff3f07f2b5)
      |                        ^
./include/generated/compile.h:8:1: error: unknown type name 'Found'
    8 | Found HIP installation: /dev/null, version 3.5.0, LLD 18.0.0"
      | ^
./include/generated/compile.h:8:10: error: expected ';' after top level declarator
    8 | Found HIP installation: /dev/null, version 3.5.0, LLD 18.0.0"
      |          ^
      |          ;
./include/generated/compile.h:8:61: warning: missing terminating '"' character [-Winvalid-pp-token]
    8 | Found HIP installation: /dev/null, version 3.5.0, LLD 18.0.0"
      |                                                             ^
In file included from ../../../../../../kernel/sony/sm8150/init/version.c:10:
In file included from ../../../../../../kernel/sony/sm8150/include/linux/module.h:9:
In file included from ../../../../../../kernel/sony/sm8150/include/linux/list.h:5:
../../../../../../kernel/sony/sm8150/include/linux/types.h:102:10: error: unknown type name '__s8'; did you mean '__u8'?
  102 | typedef         __s8            int8_t;
      |                 ^~~~
      |                 __u8
../../../../../../kernel/sony/sm8150/include/uapi/asm-generic/int-ll64.h:21:23: note: '__u8' declared here
   21 | typedef unsigned char __u8;
      |                       ^
../../../../../../kernel/sony/sm8150/init/version.c:46:26: error: expected ';' after top level declarator
   46 |         LINUX_COMPILE_HOST ") (" LINUX_COMPILER ") " UTS_VERSION "\n";
      |                                 ^
      |                                 ;
../../../../../../kernel/sony/sm8150/init/version.c:51:6: error: expected ';' after top level declarator
   51 |         " (" LINUX_COMPILER ") %s\n";
      |             ^
      |             ;
2 warnings and 5 errors generated.